# Generated by Django 2.0 on 2019-03-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_package_product'),
        ('Invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='items',
            field=models.ManyToManyField(to='Invoice.Item'),
        ),
    ]
